"""Canonical mappings for abbreviated ESPN fantasy-stat export fields.

The scraper normalizes ESPN API keys before writing CSV data used by this
application. Future features must use these schemas to resolve a requested
statistic rather than infer meanings from abbreviated column names.
"""

from typing import Final


ESPN_TO_SQLITE_NAMES: Final[dict[str, str]] = {
    "G": "G",
    "A": "A",
    "PIM": "PIM",
    "PPG": "PPG",
    "PPA": "PPA",
    "19": "19",
    "SHG": "SHG",
    "SHA": "SHA",
    "PPP": "PPP",
    "SHP": "SHP",
    "STPG": "STPG",
    "STPA": "STPA",
    "STP": "STP",
    "GWG": "GWG",
    "HAT": "HAT",
    "SOG": "SOG",
    "HIT": "HIT",
    "BLK": "BLK",
    "DEF": "DEF",
    "FOW": "FOW",
    "FOL": "FOL",
    "TTOI ?": "TTOI",
    "ATOI": "ATOI",
    "GP": "GP",
    "5": "_5",
    "12": "_12",
    "16": "PTS",
    "25": "_25",
    "30": "GP",
    "35": "_35",
    "36": "_36",
    "37": "_37",
    "99": "_99",
    "+/-": "P_M",
    "GS": "GS",
    "W": "W",
    "L": "L",
    "SA": "SA",
    "GA": "GA",
    "SV": "SV",
    "SO": "SO",
    "OTL": "OTL",
    "MIN ?": "MIN",
    "GAA": "GAA",
    "SV%": "SVP",
}


SQLITE_COLUMN_DESCRIPTIONS: Final[dict[str, str]] = {
    "id": "player id",
    "name": "player name",
    "active": "flag to indicate if player is active",
    "position_type": "player position type (Skater or Goalie)",
    "position": "player position (Forward, Defencemen, Goalie)",
    "year": "year",
    "draft_pick": "draft pick #",
    "draft_keeper": "flag to indicate if player was kept from previous year as a keeper",
    "draft_price": "draft price",
    "draft_cap_percentage": "draft price as a percentage of the total draft cap for that year",
    "FP": "fantasy points",
    "FP_AVG": "fantasy points average",
    "G": "goals",
    "A": "assist",
    "P_M": "plus/minus",
    "PTS": "points",
    "PIM": "penalty minutes",
    "PPG": "power play goals",
    "PPA": "power play assists",
    "SHG": "short handed goals",
    "SHA": "short handed assists",
    "PPP": "power play points",
    "SHP": "short handed points",
    "STPG": "special teams goals",
    "STPA": "special teams assists",
    "STP": "special teams points",
    "GWG": "game winning goals",
    "FOW": "face-off wins",
    "FOL": "face-off losses",
    "TTOI": "time on ice",
    "ATOI": "average time on ice",
    "HAT": "hat tricks",
    "SOG": "shots_on_goal",
    "HIT": "hits",
    "BLK": "blocks",
    "DEF": "defensemen points",
    "GP": "games played",
    "19": "???",
    "_5": "???",
    "_12": "win percentage",
    "_16": "points",
    "_25": "???",
    "_35": "???",
    "_36": "???",
    "_37": "???",
    "_99": "???",
    "GS": "games started",
    "W": "wins",
    "L": "losses",
    "SA": "shots against",
    "GA": "goals against",
    "SV": "saves",
    "SO": "shutouts",
    "OTL": "overtime losses",
    "MIN": "minutes played",
    "GAA": "goals against average",
    "SVP": "save percentage",
}
